### Get all the models
GET http://localhost:8080/api/data/model_file
Content-Type: application/json

### Get Seele model
GET http://localhost:8080/api/data/model_file/1
Content-Type: application/json

### Create a new model file
POST http://localhost:8080/api/data/model_file
Content-Type: application/json

{
    "idModelFile": 100,
    "nameModel": "test",
    "versionNumber": "1.0"
}

### Update model file
PUT http://localhost:8080/api/data/model_file/100
Content-Type: application/json

{
    "nameModel": "test edit",
    "versionNumber": "1.0"
}

### Delete model file
DELETE http://localhost:8080/api/data/model_file/100
Content-Type: application/json